### ISSUE TITLE
پیشنهاد تغییر فونت و اصلاح لیوت‌بندی

### ISSUE THREAD

**Issue by man4toman** [zohre1023/Persian-The-Road-to-learn-React#2]
ضمن تشکر از کار خوبتون
چند پیشنهاد دارم:

- فونت فارسی برای کتاب الکترونیکی مناسب نیست و باعث خستگی میشه
- فونت کدهاهم نیاز هست اصلاح بشه و از یک فونت مناسب برای خوانایی بیشتر استفاده بشه
- لیوت کار هم بعضا باید اصلاح بشه، صفحاتی داریم که فقط یک خط درشون هست و میشه با کمی اصلاح اونها رو درست کرد

تشکر

**Comment by zohre1023** [comment]
ممنونم بابت نظراتتون. حتما در اولین فرصت
